### ISSUE TITLE
Not able to view binding type AmqpAdapterBinding in the WCF Custom adapter 

### ISSUE THREAD

**Issue by Aarthi1607** [AbdelazizElbaz/AMQPBizTalkAdapter#2]
Added the details in the machine config files as per https://github.com/AbdelazizElbaz/AMQPBizTalkAdapter still not able to view the binding type in the drop down of wcf -custom adapter. Am I missing something here?

**Comment by AbdelazizElbaz** [comment]
Yoi must add it in the 32 and 64 version of machine config and restart you admin console

**Comment by Aarthi1607** [comment]
Yes added it in both versions. Restarted admin console and even the machine , still not seeing it .

**Comment by Aarthi1607** [comment]
Thank you so much i added all the dlls from https://github.com/AbdelazizElbaz/AMQPBizTalkAdapter/tree/master/src/ExternalReferences now i am able to see the binding

**Comment by Aarthi1607** [comment]
I am getting this error now , do you know why ?
StartListener::Error in AMQPBizTalkAdapterInboundHandler.StartListener : [RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> System.IO.IOException: connection.start was never received, likely due to a network timeout
   at RabbitMQ.Client.Framing.Impl.Connection.StartAndTune()
   at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
   at RabbitMQ.Client.Framing.Impl.Connection..ctor(IConnectionFactory factory, Boolean insist, IFrameHandler frameHandler, String clientProvidedName)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IEndpointResolver endpoints)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection()
   at AMQPBizTalkAdapter.AmqpReceiverBase.Start(TimeSpan timeout, MethodTracer methodTracer)
   at AMQPBizTalkAdapter.AmqpRabbitMqNotificationReceiver.StartListener(TimeSpan timeout, MethodTracer methodTracer)
   at AMQPBizTalkAdapter.AMQPBizTalkAdapterInboundHandler.StartListener(String[] actions, TimeSpan timeout)]

**Comment by AbdelazizElbaz** [comment]
Chech you url and you must add login/password

**Comment by Aarthi1607** [comment]
URL looks fine amqp://localhost:15672/Queue/TestNew , I have added login and password on the receive location.

**Comment by AbdelazizElbaz** [comment]
Do you have a message broker started in your machine? 
The error tell that your localhost:15672 is not reachable

**Comment by Aarthi1607** [comment]
I am sorry , I'm very new to using Rabbit MQ with BizTalk , can you please tell me how to start a message broker ?

**Comment by AbdelazizElbaz** [comment]
You can start with 

Rabbit ma getstarted

https://www.rabbitmq.com/download.html
